[package]
name = "toku_bench_common"
version = "0.0.1"
authors = ["Helselia Inc."]
edition = "2018"

[dependencies]
failure = "0.1"
toku_client = { path = "../../toku_client" }
log = "0.4"
fern = "0.5"
chrono = "0.4"
